### ISSUE TITLE
Regarding Sign Up Validation

### ISSUE THREAD

**Issue by ank1tzzz** [Suraj-1000/Collab-HRMS#2]
![image](https://github.com/Suraj-1000/Collab-HRMS/assets/127822750/604c0bc5-6f54-46aa-9df7-743564921c4d)

Dear Suraj, please apply validation in the signup.php file and make the necessary changes.
Thank you!

**Comment by Suraj-1000** [comment]
![Screenshot 2024-04-20 201509](https://github.com/Suraj-1000/Collab-HRMS/assets/127823021/47838b0d-e7ed-4980-b247-e20dc3eb3091)


Sure, I've implemented validation in the signup.php file and made the necessary adjustments. Thank you for entrusting me with the task.
