### ISSUE TITLE
Forget password issue

### ISSUE THREAD

**Issue by ank1tzzz** [Suraj-1000/Collab-HRMS#3]
![image](https://github.com/Suraj-1000/Collab-HRMS/assets/127822750/f3016bdf-6a11-4388-b210-372d27bbd90a)

It is not working, please fix it.

**Comment by Suraj-1000** [comment]
The code is correct the missing part is you need to include the rest_token column in the  table named users 
![image](https://github.com/Suraj-1000/Collab-HRMS/assets/127823021/c961cf9c-d1fb-4ee9-8d45-74bb173fddbf)
